services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ../usebb:/var/www/html
  db:
    image: mysql:5
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: usebb
      MYSQL_ROOT_PASSWORD: root
    command:
      - --sql_mode=
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  mysql-volume:
